Add minimum code coverage to CI testing

diff --git a/share/ramble/cloud-build/ramble-pr-validation.yaml b/share/ramble/cloud-build/ramble-pr-validation.yaml
--- a/share/ramble/cloud-build/ramble-pr-validation.yaml
+++ b/share/ramble/cloud-build/ramble-pr-validation.yaml
@@ -59,7 +59,10 @@ steps:
         # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
         unit_err=$$?
 
-        coverage report -m
+        coverage report -m --fail-under=74
+        # $$ characters are required for cloud-build:
+        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
+        coverage_err=$$?
 
         error=0
         # $$ characters are required for cloud-build:
@@ -95,6 +98,21 @@ steps:
           echo " ***** Unit tests failed"
           error=1
         fi
+
+        # $$ characters are required for cloud-build:
+        # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
+        if [ $$coverage_err -gt 0 ]; then
+          if [ $$coverage_err == 2 ]; then
+            echo "Code coverage dropped below the minimum level."
+            echo " ***** Coverage decreased"
+          else
+            echo "Code coverage report generation failed."
+            echo " ***** Coverage report generic error"
+          fi
+
+          error=1
+        fi
+
 
         # $$ characters are required for cloud-build:
         # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
