Use `coverage run` for more accurate coverage numbers
Previously when using `pytest-cov`, it did not capture lines that are executed as part of module initializations. One reason of relying on `pytest-cov` is becuase that handles subprocess calls properly.
In newer versions of `coverage.py`, the "subprocess" patch config now handles this correctly, so we can use `coverage run` directly for a more accurate coverage report.

diff --git a/share/ramble/cloud-build/ramble-pr-unit-tests.yaml b/share/ramble/cloud-build/ramble-pr-unit-tests.yaml
--- a/share/ramble/cloud-build/ramble-pr-unit-tests.yaml
+++ b/share/ramble/cloud-build/ramble-pr-unit-tests.yaml
@@ -56,15 +56,21 @@ steps:
         # $$ characters are required for cloud-build:
         # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
         if [ $$coverage_err -gt 0 ]; then
-          if [ $$coverage_err == 2 ]; then
-            echo "Code coverage dropped below the minimum level."
-            echo " ***** Coverage decreased"
-          else
-            echo "Code coverage report generation failed."
-            echo " ***** Coverage report generic error"
-          fi
+          python3 -c 'import sys; exit(0 if sys.version_info >= (3, 9) else 1)'
+          py_version_check_err=$$?
+          if [ $$py_version_check_err -eq 0 ]; then
+            if [ $$coverage_err == 2 ]; then
+              echo "Code coverage dropped below the minimum level."
+              echo " ***** Coverage decreased"
+            else
+              echo "Code coverage report generation failed."
+              echo " ***** Coverage report generic error"
+            fi
 
-          error=1
+            error=1
+          else
+            echo "Skipping coverage check for python version < 3.9, as the coverage number is not accurate"
+          fi
         fi
 
         # $$ characters are required for cloud-build:
